/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct suma_1_argument {
	double arg1;
	double arg2;
};
typedef struct suma_1_argument suma_1_argument;

#define SUMAPROG 0x20000001
#define SUMAVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(double , double , CLIENT *);
extern  double * suma_1_svc(double , double , struct svc_req *);
extern int sumaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
extern int sumaprog_1_freeresult ();
#endif /* K&R C */

struct resta_1_argument {
	double arg1;
	double arg2;
};
typedef struct resta_1_argument resta_1_argument;

#define RESTAPROG 0x20000002
#define RESTAVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESTA 1
extern  double * resta_1(double , double , CLIENT *);
extern  double * resta_1_svc(double , double , struct svc_req *);
extern int restaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESTA 1
extern  double * resta_1();
extern  double * resta_1_svc();
extern int restaprog_1_freeresult ();
#endif /* K&R C */

struct multi_1_argument {
	double arg1;
	double arg2;
};
typedef struct multi_1_argument multi_1_argument;

#define MULTIPROG 0x20000003
#define MULTIVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTI 1
extern  double * multi_1(double , double , CLIENT *);
extern  double * multi_1_svc(double , double , struct svc_req *);
extern int multiprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTI 1
extern  double * multi_1();
extern  double * multi_1_svc();
extern int multiprog_1_freeresult ();
#endif /* K&R C */

struct div_1_argument {
	double arg1;
	double arg2;
};
typedef struct div_1_argument div_1_argument;

#define DIVPROG 0x20000004
#define DIVVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define DIV 1
extern  double * div_1(double , double , CLIENT *);
extern  double * div_1_svc(double , double , struct svc_req *);
extern int divprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DIV 1
extern  double * div_1();
extern  double * div_1_svc();
extern int divprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_suma_1_argument (XDR *, suma_1_argument*);
extern  bool_t xdr_resta_1_argument (XDR *, resta_1_argument*);
extern  bool_t xdr_multi_1_argument (XDR *, multi_1_argument*);
extern  bool_t xdr_div_1_argument (XDR *, div_1_argument*);

#else /* K&R C */
extern bool_t xdr_suma_1_argument ();
extern bool_t xdr_resta_1_argument ();
extern bool_t xdr_multi_1_argument ();
extern bool_t xdr_div_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
