/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package calculadora;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-03-28")
public class DivideEntre0 extends org.apache.thrift.TException implements org.apache.thrift.TBase<DivideEntre0, DivideEntre0._Fields>, java.io.Serializable, Cloneable, Comparable<DivideEntre0> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DivideEntre0");

  private static final org.apache.thrift.protocol.TField CODIGO_FIELD_DESC = new org.apache.thrift.protocol.TField("codigo", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CADENA_FIELD_DESC = new org.apache.thrift.protocol.TField("cadena", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DivideEntre0StandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DivideEntre0TupleSchemeFactory();

  public int codigo; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String cadena; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CODIGO((short)1, "codigo"),
    CADENA((short)2, "cadena");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODIGO
          return CODIGO;
        case 2: // CADENA
          return CADENA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CODIGO_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODIGO, new org.apache.thrift.meta_data.FieldMetaData("codigo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CADENA, new org.apache.thrift.meta_data.FieldMetaData("cadena", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DivideEntre0.class, metaDataMap);
  }

  public DivideEntre0() {
  }

  public DivideEntre0(
    int codigo,
    java.lang.String cadena)
  {
    this();
    this.codigo = codigo;
    setCodigoIsSet(true);
    this.cadena = cadena;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DivideEntre0(DivideEntre0 other) {
    __isset_bitfield = other.__isset_bitfield;
    this.codigo = other.codigo;
    if (other.isSetCadena()) {
      this.cadena = other.cadena;
    }
  }

  public DivideEntre0 deepCopy() {
    return new DivideEntre0(this);
  }

  @Override
  public void clear() {
    setCodigoIsSet(false);
    this.codigo = 0;
    this.cadena = null;
  }

  public int getCodigo() {
    return this.codigo;
  }

  public DivideEntre0 setCodigo(int codigo) {
    this.codigo = codigo;
    setCodigoIsSet(true);
    return this;
  }

  public void unsetCodigo() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CODIGO_ISSET_ID);
  }

  /** Returns true if field codigo is set (has been assigned a value) and false otherwise */
  public boolean isSetCodigo() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CODIGO_ISSET_ID);
  }

  public void setCodigoIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CODIGO_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCadena() {
    return this.cadena;
  }

  public DivideEntre0 setCadena(@org.apache.thrift.annotation.Nullable java.lang.String cadena) {
    this.cadena = cadena;
    return this;
  }

  public void unsetCadena() {
    this.cadena = null;
  }

  /** Returns true if field cadena is set (has been assigned a value) and false otherwise */
  public boolean isSetCadena() {
    return this.cadena != null;
  }

  public void setCadenaIsSet(boolean value) {
    if (!value) {
      this.cadena = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CODIGO:
      if (value == null) {
        unsetCodigo();
      } else {
        setCodigo((java.lang.Integer)value);
      }
      break;

    case CADENA:
      if (value == null) {
        unsetCadena();
      } else {
        setCadena((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CODIGO:
      return getCodigo();

    case CADENA:
      return getCadena();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CODIGO:
      return isSetCodigo();
    case CADENA:
      return isSetCadena();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof DivideEntre0)
      return this.equals((DivideEntre0)that);
    return false;
  }

  public boolean equals(DivideEntre0 that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_codigo = true;
    boolean that_present_codigo = true;
    if (this_present_codigo || that_present_codigo) {
      if (!(this_present_codigo && that_present_codigo))
        return false;
      if (this.codigo != that.codigo)
        return false;
    }

    boolean this_present_cadena = true && this.isSetCadena();
    boolean that_present_cadena = true && that.isSetCadena();
    if (this_present_cadena || that_present_cadena) {
      if (!(this_present_cadena && that_present_cadena))
        return false;
      if (!this.cadena.equals(that.cadena))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + codigo;

    hashCode = hashCode * 8191 + ((isSetCadena()) ? 131071 : 524287);
    if (isSetCadena())
      hashCode = hashCode * 8191 + cadena.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DivideEntre0 other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCodigo()).compareTo(other.isSetCodigo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCodigo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.codigo, other.codigo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCadena()).compareTo(other.isSetCadena());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCadena()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cadena, other.cadena);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DivideEntre0(");
    boolean first = true;

    sb.append("codigo:");
    sb.append(this.codigo);
    first = false;
    if (!first) sb.append(", ");
    sb.append("cadena:");
    if (this.cadena == null) {
      sb.append("null");
    } else {
      sb.append(this.cadena);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DivideEntre0StandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DivideEntre0StandardScheme getScheme() {
      return new DivideEntre0StandardScheme();
    }
  }

  private static class DivideEntre0StandardScheme extends org.apache.thrift.scheme.StandardScheme<DivideEntre0> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DivideEntre0 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODIGO
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.codigo = iprot.readI32();
              struct.setCodigoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CADENA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cadena = iprot.readString();
              struct.setCadenaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DivideEntre0 struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CODIGO_FIELD_DESC);
      oprot.writeI32(struct.codigo);
      oprot.writeFieldEnd();
      if (struct.cadena != null) {
        oprot.writeFieldBegin(CADENA_FIELD_DESC);
        oprot.writeString(struct.cadena);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DivideEntre0TupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public DivideEntre0TupleScheme getScheme() {
      return new DivideEntre0TupleScheme();
    }
  }

  private static class DivideEntre0TupleScheme extends org.apache.thrift.scheme.TupleScheme<DivideEntre0> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DivideEntre0 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCodigo()) {
        optionals.set(0);
      }
      if (struct.isSetCadena()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCodigo()) {
        oprot.writeI32(struct.codigo);
      }
      if (struct.isSetCadena()) {
        oprot.writeString(struct.cadena);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DivideEntre0 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.codigo = iprot.readI32();
        struct.setCodigoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.cadena = iprot.readString();
        struct.setCadenaIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

